using System.ComponentModel.DataAnnotations;

namespace cxc_tool_asp.Models;

/// <summary>
/// View model for creating or editing users.
/// </summary>
public class UserViewModel
{
    /// <summary>
    /// Hidden field for user ID during edits. Null for new users.
    /// </summary>
    public Guid? Id { get; set; }

    /// <summary>
    /// The name displayed for the user. Should be unique.
    /// </summary>
    [Required(ErrorMessage = "Display Name is required.")]
    [StringLength(50, MinimumLength = 3, ErrorMessage = "Display Name must be between 3 and 50 characters.")]
    [Display(Name = "Display Name")]
    public required string DisplayName { get; set; }

    /// <summary>
    /// The password for the user. Required for new users. Optional for edits (if not changing password).
    /// </summary>
    [DataType(DataType.Password)]
    [StringLength(100, MinimumLength = 2, ErrorMessage = "Password must be at least 2 characters long.")]
    [Display(Name = "Password")]
    public string? Password { get; set; } // Nullable for edits where password isn't changed

    /// <summary>
    /// Confirmation field for the password. Must match Password.
    /// </summary>
    [DataType(DataType.Password)]
    [Display(Name = "Confirm Password")]
    [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
    public string? ConfirmPassword { get; set; }

    /// <summary>
    /// Indicates if the user has administrative privileges.
    /// </summary>
    [Display(Name = "Is Administrator?")]
    public bool IsAdmin { get; set; } = false;

    // Note: FolderName is generated by the service, not set by the user directly.
}
