using System.ComponentModel.DataAnnotations;

namespace cxc_tool_asp.Models;

/// <summary>
/// Represents a user in the application.
/// </summary>
public record User
{
    /// <summary>
    /// Unique identifier for the user (e.g., for internal use or potential future DB migration).
    /// </summary>
    public Guid Id { get; init; } = Guid.NewGuid();

    /// <summary>
    /// The name displayed for the user. Should be unique.
    /// </summary>
    [Required]
    [StringLength(50, MinimumLength = 3)]
    public required string DisplayName { get; init; }

    /// <summary>
    /// The hashed password for the user.
    /// </summary>
    [Required]
    public required string PasswordHash { get; init; }

    /// <summary>
    /// The unique folder name assigned to the user for storing their files.
    /// Generated by the system (e.g., 2 letters + optional number).
    /// </summary>
    [Required]
    [RegularExpression(@"^[a-zA-Z]{2}\d?$")] // Example: AA, AB1 etc. Needs refinement based on generation logic.
    public required string FolderName { get; init; }

    /// <summary>
    /// Indicates if the user has administrative privileges.
    /// </summary>
    public bool IsAdmin { get; init; } = false;
}
